chats/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.chats, name="chats"),
    path("<str:username>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
]

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profile/<username>/", views.profile_view, name="view"),
    path("profile/<username>/edit/", views.edit_profile_view, name="edit"),
    path("addfriend/<str:username>", views.add_friend, name="add_friend"),
    path("removefriend/<str:username>", views.remove_friend, name="remove_friend"),
]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include

import posts.views
from mainpage import views as mainpage_views
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", mainpage_views.home_view, name="empty_address"),
    path("", include("login.urls")),
    path("home/", include("mainpage.urls")),
    path("chats/", include("chats.urls")),
    path("", mainpage_views.home_view, name="empty_address"),
    path("", include("search.urls")),
    path("", include(("profiles.urls", "profile"), namespace="profile")),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='profiles/password_change_done.html'),
         name="password_change_done"),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='profiles/password_change.html'),
         name="password_change"),
    path('friends/', mainpage_views.view_friends, name='friends'),
    path('friend_requests/', mainpage_views.view_friend_requests, name='friend_requests'),
    path("posts/", include("posts.urls"), name="posts"),
    path('news/', include(([path('', posts.views.news)], 'posts')))
]

urlpatterns += staticfiles_urlpatterns()

profiles/models.py
from django.db import models

profiles/forms.py
from django import forms

from accounts.models import User


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "email",
            "phone",
            "bio",
            "first_name",
            "last_name",
        ]

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        try:
            user = User.objects.exclude(username=self.instance.username).get(
                email=email
            )
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % email)

    def save(self, commit=True):
        profile = super(AccountUpdateForm, self).save(commit=False)
        profile.email = self.cleaned_data["email"].lower()
        profile.phone = self.cleaned_data["phone"]
        profile.bio = self.cleaned_data["bio"]
        profile.first_name = self.cleaned_data["first_name"]
        profile.last_name = self.cleaned_data["last_name"]
        if commit:
            profile.save()
        return profile

profiles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from accounts.models import User
from django.conf import settings
from .forms import AccountUpdateForm
from accounts.models import Friends
from mainpage.views import get_friend_list


def check_friendship(user_1, user_2):
    if Friends.objects.filter(user=user_1, friend=user_2).exists():
        return not Friends.objects.get(user=user_1, friend=user_2).is_request
    elif Friends.objects.filter(user=user_2, friend=user_1).exists():
        return not Friends.objects.get(user=user_2, friend=user_1).is_request
    return False


def profile_view(request, *args, **kwargs):
    context = {}
    username = kwargs.get("username")

    try:
        user_profile = User.objects.get(username=username)
    except User.DoesNotExist:
        return HttpResponse("That user doesn't exist.")

    if user_profile:
        context["username"] = user_profile.username
        context["first_name"] = user_profile.first_name
        context["last_name"] = user_profile.last_name
        context["email"] = user_profile.email
        context["phone"] = user_profile.phone
        context["bio"] = user_profile.bio

    is_self = True
    current_user = request.user
    is_logged_in = user_profile.is_authenticated

    if not is_logged_in:
        is_self = False
    elif current_user.username != username:
        is_self = False

    is_friend = check_friendship(current_user, user_profile)

    # For status request: 0 = not requested, 1 = requested by me, 2 = requested by other
    context["status_request"] = 0
    if Friends.objects.filter(user=current_user, friend=user_profile).exists():
        context["status_request"] = 1 if Friends.objects.get(user=current_user, friend=user_profile).is_request else 0
    elif Friends.objects.filter(user=user_profile, friend=current_user).exists():
        context["status_request"] = 2 if Friends.objects.get(user=user_profile, friend=current_user).is_request else 0
    context["title"] = user_profile
    context["is_self"] = is_self
    context["is_logged_in"] = is_logged_in
    context["is_friend"] = is_friend
    context["BASE_URL"] = settings.BASE_URL

    return render(request, "profiles/profile.html", context)


def add_friend(request, username):
    if not request.user.is_authenticated:
        return redirect("login")

    friend = User.objects.get(username=username)
    user = User.objects.get(username=request.user.username)

    # If the friend has sent a friend request
    # Accept the friend request
    if Friends.objects.filter(user=friend, friend=user).exists():
        friendship = Friends.objects.get(user=friend, friend=user)
        if friendship.is_request:
            friendship.is_request = False
            friendship.save()
            friendship = Friends(user=user, friend=friend)
            friendship.is_request = False
            friendship.save()
            print("Friend added")
        else:
            print("Friend already exists")
    # If the friend has not sent a friend request
    elif not Friends.objects.filter(user=user, friend=friend).exists():
        friendship = Friends(user=user, friend=friend, is_request=True)
        friendship.save()
        print("Request sent")
    else:
        print("Already sent a request")

    return redirect("profile:view", username=friend.username)


def remove_friend(request, username):
    if not request.user.is_authenticated:
        return redirect("login")

    friend = User.objects.get(username=username)
    user = User.objects.get(username=request.user.username)

    if Friends.objects.filter(user=user, friend=friend).exists():
        friendship = Friends.objects.get(user=user, friend=friend)
        friendship.delete()
        print("Friend removed")

    if Friends.objects.filter(user=friend, friend=user).exists():
        friendship = Friends.objects.get(user=friend, friend=user)
        friendship.delete()
        print("Friend removed")

    return redirect("profile:view", username=friend.username)


def edit_profile_view(request, *args, **kwargs):
    if not request.user.is_authenticated:
        return redirect("login")

    username = kwargs.get("username")
    user = User.objects.get(username=username)

    if user.username != request.user.username:
        return HttpResponse("You can not edit someone else profile")

    context = {"title": "Edit profile"}
    if request.POST:
        form = AccountUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            form.clean_email()
            return redirect("profile:view", username=user.username)
        else:
            form = AccountUpdateForm(
                request.POST,
                instance=request.user,
                initial={
                    "username": user.username,
                    "email": user.email,
                    "phone": user.phone,
                    "bio": user.bio,
                    "first_name": user.first_name,
                    "last_name": user.last_name,
                },
            )
            context["form"] = form
    else:
        form = AccountUpdateForm(
            initial={
                "username": user.username,
                "email": user.email,
                "phone": user.phone,
                "bio": user.bio,
                "first_name": user.first_name,
                "last_name": user.last_name,
            }
        )
    context["form"] = form
    return render(request, "profiles/edit_profile.html", context)

profiles/templates/profiles/edit_profile.html
{% extends 'base_mainpage.html' %}

{% block head %}
    <title>Edit profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles/edit_profile.css' %}">

{% endblock %}


{% block content %}
    <div class="register-form">
        <form method="post">{% csrf_token %}
            <div class="form-container">
                <div class="form-element">
                    <input name="first_name" placeholder="First Name" required="false"
                           autofocus value={{ form.initial.first_name }}>
                    <label style="margin-left: -100%" id="my" class="fa fa-user" for="email"></label>
                </div>

                <div class="form-element">
                    <input name="last_name" placeholder="Last Name" required="false"
                           autofocus value={{ form.initial.last_name }}>
                    <label style="margin-left: -100%" id="my" class="fa fa-user" for="email"></label>
                </div>
                <div class="form-element">
                    <input name="email" placeholder="Email address" required="false"
                           autofocus value={{ form.initial.email }}>
                    <label style="margin-left: -100%" id="my" class="fa fa-at" for="email"></label>

                </div>

                <div class="form-element">
                    <input name="phone" placeholder="Phone" required="false"
                           autofocus value={{ form.initial.phone }}>
                    <label style="margin-left: -100%" id="my" class="fa fa-phone" for="email"></label>
                </div>

                <div class="form-element">
                    <input name="bio" placeholder="Bio" required="false"
                           autofocus value={{ form.initial.bio }}>
                    <label style="margin-left: -100%" id="my" class="fa fa-info" for="email"></label>
                </div>

                {% for field in form %}
                    <p>
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                {% endfor %}

                {% if form.non_field_errors %}
                    <div style="color: red">
                        <p>{{ form.non_field_errors }}</p>
                    </div>
                {% endif %}

{#                <button type="submit">Save</button>#}

                <div class="form-element ">
                    <p>
                        <button type="submit" class="button-1" id="register-button">Save</button>
                    </p>
                </div>

            </div>
        </form>
    </div>

{% endblock %}

profiles/templates/profiles/password_change.html
{% extends 'base_mainpage.html' %}

{% block head %}
    <title>Edit password</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles/edit_profile.css' %}">

{% endblock %}
{% block content %}
    <div>
        <form id="id_password_change_form" method="POST">{% csrf_token %}
            <h1 style="color: white">Change password</h1>
            <div class="form-container">
                <div class="form-element">
                    <input name="old_password" placeholder="Old password" type="password" id="id_old_password"
                           required="true">
                </div>
                <div class="form-element">
                    <input name="new_password1" placeholder="New password" type="password" id="id_new_password1"
                           required="true">
                </div>
                <div class="form-element">
                    <input name="new_password2" placeholder="Confirm password" type="password" id="id_new_password2"
                           required="true">
                </div>
                <div class="form-element ">
                    <p>
                        <button id="id_submit_btn" type="submit" class="button-1">Update</button>
                    </p>
                </div>
            </div>
        </form>
    </div>
    <div>
        <br><br><br><br><br><br><br><br><br>
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color: #fffb00; font-size: x-large">{{ error }}</p>
            {% endfor %}
        {% endfor %}

    </div>

{% endblock %}

profiles/templates/profiles/password_change_done.html
{% extends 'base_mainpage.html' %}

{% block head %}
    <title>Success</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles/edit_profile.css' %}">

{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 style="color: white">Success!</h1>
            </div>
        </div>
    </div>

{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'base_mainpage.html' %}

{% block head %}
    <title>Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles/edit_profile.css' %}">

    <link rel="stylesheet" href="{% static 'profiles/profile.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="user-info">
            <p-label>Username:</p-label>
            <p-text> @{{ username }}</p-text>

            <p-label>Name:</p-label>
            <p-text>{{ first_name }} {{ last_name }}</p-text>

            <p-label>Email:</p-label>
            <p-text>{{ email }}</p-text>

            <p-label>Telephone:</p-label>
            <p-text>{{ phone }}</p-text>

            <p-label>Bio:</p-label>
            <p-text>{{ bio }}</p-text>

            <p-label>Is logged in:</p-label>
            {% if is_logged_in %}
                <p-text>Yes</p-text> {% else %}
                <p-text>No</p-text> {% endif %}
            {% if is_self %}
                <button class="button-1 profile">
                    <a href="{% url 'profile:edit' username=request.user.username %}">Update information</a>
                </button>
                <button class="button-1 profile">
                    <a href="{% url 'password_change' %}">Change password</a>
                </button>
            {% elif is_friend %}
                <h2>You are friends!</h2>
                <button class="button-1 profile">
                    <a href="{% url 'profile:remove_friend' username=username %}">Remove friend</a>
                </button>
            {% elif status_request == 2 %}
                <h2>You have a friend request!</h2>
                <button class="button-1 profile">
                    <a href="{% url 'profile:add_friend' username=username %}">Accept friend request</a>
                </button>
            {% elif status_request == 1 %}
                <h2>You sent a friend request!</h2>
            {% else %}
                <h2>You are not friends!</h2>
                <button class="button-1 profile">
                    <a href="{% url 'profile:add_friend' username=username %}">Send friend request</a>
                </button>
            {% endif %}
        </div>
        {% if is_self %}
            <button class= "button-1 posts">
                <a href="/posts/">Show my posts</a>
            </button>
            <button-1 class="button-1 posts">
                <a href="{% url 'create_post' %}">Create new post</a>
            </button-1>
        {% endif %}


    </div>

{% endblock %}

</body>