chats/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.chats, name="chats"),
    path("<str:username>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
]

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profile/<username>/", views.profile_view, name="view"),
    path("profile/<username>/edit/", views.edit_profile_view, name="edit"),
    path("addfriend/<str:username>", views.add_friend, name="add_friend"),
    path("removefriend/<str:username>", views.remove_friend, name="remove_friend"),
]

search/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("search/", views.search_view, name="search")
]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include

import posts.views
from mainpage import views as mainpage_views
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", mainpage_views.home_view, name="empty_address"),
    path("", include("login.urls")),
    path("home/", include("mainpage.urls")),
    path("chats/", include("chats.urls")),
    path("", mainpage_views.home_view, name="empty_address"),
    path("", include("search.urls")),
    path("", include(("profiles.urls", "profile"), namespace="profile")),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='profiles/password_change_done.html'),
         name="password_change_done"),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='profiles/password_change.html'),
         name="password_change"),
    path('friends/', mainpage_views.view_friends, name='friends'),
    path('friend_requests/', mainpage_views.view_friend_requests, name='friend_requests'),
    path("posts/", include("posts.urls"), name="posts"),
    path('news/', include(([path('', posts.views.news)], 'posts')))
]

urlpatterns += staticfiles_urlpatterns()

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms

search/views.py
from django.shortcuts import render, redirect
from accounts.models import User
from mainpage.views import get_friend_list
from accounts.models import Friends


def search_view(request):
    if not request.user.is_authenticated:
        return redirect("login")

    context = {}

    # <input type="text" name="q"/>
    search_query = request.GET.get("q")

    if search_query is not None:
        # Using filter will return multiple rows
        # icontains doesn't care about lower case and upper case
        if len(search_query) > 0:
            search_results = User.objects.filter(username__icontains=search_query)
            accounts = []
            for account in search_results:
                if Friends.objects.filter(user=request.user, friend=account).exists():
                    accounts.append((account, True))
                else:
                    accounts.append((account, False))
            if len(accounts) == 0:
                error = "Can not find such users"
                context = {"title": "Search", "accounts": accounts, "error": error}
            else:
                context = {"title": "Search", "accounts": accounts}
        else:
            error = "Please pass something to search"
            context = {"title": "Search", "error": error}

    return render(request, "search/search.html", context)

search/templates/search/search.html
{% extends 'base_mainpage.html' %}

{% block head %}
    <title>Search</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'search/search.css' %}">
{% endblock %}

{% block content %}
    <h2 style="color: white">Search for other users</h2>
    <form action="/search" method="GET">
        <input class="input-text" type="text" name="q"/>
        <input class="send-button" type="submit" value="Search"/>
    </form>

    {% if error %}
        <p style="color:red">ERROR: {{ error }}</p>
    {% else %}
        {% if accounts %}
            <div>
                {% for account in accounts %}
                    <div class="search-result">
                        <a href="{% url 'profile:view' username=account.0.username %}">
                            <h4>{{ account.0 }} - {{ account.0.username }}</h4>
                            {% if account.1 %}
                                <p>Your friend</p>
                            {% else %}
                                {% if account.0 != request.user %}
                                    <p>Not your friend</p>
                                {% endif %}
                            {% endif %}
                            {% if account.0 == request.user %}
                                <p>
                                    This is you
                                </p>
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endif %}

{% endblock %}